name: Deploy new version of application

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Check repo
        uses: actions/checkout@v2

      - name: Set image name variable
        run: |
          timestamp=$(date +%Y%m%d%H%M%S)
          version=$(echo "$timestamp" | sed -E 's/(.*)/v\1/')
          prefix="dev-"
          if [ "$GITHUB_REF" == "refs/heads/master" ]; then
            prefix="prod-"
          fi
          echo "IMAGE_NAME=${prefix}cherryswap_$version" >> $GITHUB_ENV

      - name: Build images
        run: docker build -t ${{ env.IMAGE_NAME }} --build-arg CHANGE_NOW_API_KEY=${{ secrets.CHANGE_NOW_API_KEY }} --build-arg CHANGE_NOW_API_URL=${{ secrets.CHANGE_NOW_API_URL }} --build-arg CHANGE_NOW_EXCHANGE_STATUS_API=${{ secrets.CHANGE_NOW_EXCHANGE_STATUS_API }} --build-arg NEXT_PUBLIC_CONTENT_API_URL=${{ secrets.NEXT_PUBLIC_CONTENT_API_URL }} .

      - name: Save image to tar
        run: docker save ${{ env.IMAGE_NAME }} -o "${{ env.IMAGE_NAME }}.tar"

      - name: Copy single file to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: '${{ env.IMAGE_NAME }}.tar'
          remote: 'images/${{ env.IMAGE_NAME }}.tar'
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Connect to server via SSH
        uses: appleboy/ssh-action@v0.1.6
        if: github.ref == 'refs/heads/master'
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker stop production || true
            docker rm production || true

            docker load -i images/${{ env.IMAGE_NAME }}.tar
            docker run --name production -d -p 3000:3000 -e CHANGE_NOW_API_KEY=${{ secrets.CHANGE_NOW_API_KEY }} -e CHANGE_NOW_API_URL=${{ secrets.CHANGE_NOW_API_URL }} -e CHANGE_NOW_EXCHANGE_STATUS_API=${{ secrets.CHANGE_NOW_EXCHANGE_STATUS_API }} -e NEXT_PUBLIC_CONTENT_API_URL=${{ secrets.NEXT_PUBLIC_CONTENT_API_URL }} ${{ env.IMAGE_NAME }}

      - name: Connect to server via SSH
        uses: appleboy/ssh-action@v0.1.6
        if: github.ref == 'refs/heads/develop'
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker stop staging || true
            docker rm staging || true

            docker load -i images/${{ env.IMAGE_NAME }}.tar
            docker run --name staging -d -p 1243:3000 -e CHANGE_NOW_API_KEY=${{ secrets.CHANGE_NOW_API_KEY }} -e CHANGE_NOW_API_URL=${{ secrets.CHANGE_NOW_API_URL }} -e CHANGE_NOW_EXCHANGE_STATUS_API=${{ secrets.CHANGE_NOW_EXCHANGE_STATUS_API }} -e NEXT_PUBLIC_CONTENT_API_URL=${{ secrets.NEXT_PUBLIC_CONTENT_API_URL }} ${{ env.IMAGE_NAME }}
